---
driver:
  name: vagrant
  customize:
    memory: 2000
    cpus: 2
    clipboard: bidirectional
    # cableconnected1: 'on'
  # ssh:
  #   insert_key: false
    # private_key_path: 
    # username: vagrant
    # password: vagrant
  # network:
    # - ["forwarded_port", {guest: 80, host: 880, auto_correct: true}]
    # - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
    # - ["private_network", {ip: "192.168.33.22"}]
  # synced_folders:
  #   - ["/Users/alexvinyar/Documents/ISO_BOX_etc/chef-packages", "/server_data"]
  #   - [".", "/home/vagrant"]

provisioner:
  name: chef_zero
  # can't use chef 13 until bug is fixed in fancy_execute
  # there is a PR that fixes fancy execute for supermarket.
  # https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/pull/51
  require_chef_omnibus: 12.19.36
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

# verifier:
#   name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      synced_folders:
      - ["/Users/<%=ENV['USER']%>/Documents/ISO_BOX_etc/chef-packages", "/server_data"]
      - [".", "/vagrant"]
    run_list:
      # - recipe[chef-server-restore::supermarket] # break out into a separate suit
      - recipe[chef-server-restore::default]
    # verifier:
    #   inspec_tests:
    #     - test/smoke/default
    attributes:
